### ISSUE TITLE
Item BUG in GUI 1.17

### ISSUE THREAD

**Issue by Fedee0** [SirOswaldo/SimpleHomes#4]
-The plugin seems to work fine, but when I open a gui what should be glass is replaced by dirt...
   -I dont think im missing something in the settings.yml

  

 --> Version Info

 - Server Version: Purpur 1.17
 - Plugin: 2.0

 - IMAGE:

![image](https://user-images.githubusercontent.com/84406177/135232367-5247f731-15d6-45f0-b157-cebdcdc41008.png)

**Comment by Fedee0** [comment]
I managed to fix, the problem was caused that the item names in the default config are not the same as in 1.17. You should add a function that detects the version and chooses what settings to put...

- Here you can find a list of 1.17 blocks: https://docs.brcdev.net/#/materials

--------------------------------------------------------------------------------

The same thing happens with sounds

- Find a list here: https://hub.spigotmc.org/javadocs/bukkit/org/bukkit/Sound.html

**Comment by SirOswaldo** [comment]
Yes i working in api to support all items

**Comment by SirOswaldo** [comment]
Fixed
