### ISSUE TITLE
Wrong plugin outdated message

### ISSUE THREAD

**Issue by PappoYT** [SirOswaldo/SimpleHomes#5]
When I login I get this message in chat:
`The plugin SimpleHomes is outdated. Current version 2.0 Latest version 2.1 Download...`

I've downloaded the most recent version from Spigot page, the file name is correct `SimpleHomes-2.1.jar` but it seems that the plugin version is still 2.0 inside.

Log > https://mclo.gs/uoUWigk

![simplehome](https://user-images.githubusercontent.com/74958346/148670592-eb4d955a-781f-45ba-8a0f-e47af4dc1a2d.PNG)

**Comment by SirOswaldo** [comment]
This was a mistake of mine for not changing it when I compiled it. It was already fixed in the latest version.
